# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Mass Testing 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
    - name: wandb login 
      run: |
        wandb login ${{ secrets.WANDB }}
      
    - name: 1 train.py --project --name   
      run: |
        python train.py --project ich_ci --name ${{ steps.vars.outputs.sha_short }}_1raw 
        
    - name: 2 train.py --cache
      run: |
        python train.py --project ich_ci --cache cache.pkl --name ${{ steps.vars.outputs.sha_short }}_2cache
        
    
    - name: 3 train.py --kfold
      run: |
        python train.py --project ich_ci --cache cache.pkl --repro --kfold 2/5 --name ${{ steps.vars.outputs.sha_short }}_3kfold
        
    - name: 4 train.py --kfold
      run: |
        python train.py --project ich_ci --cache cache.pkl --repro --skfold 3/5 --name ${{ steps.vars.outputs.sha_short }}_4skfold
        
    - name: 5 train.py --repro1  # put repro to the end to ensure all args worked
      run: |
        python train.py --project ich_ci --cache cache.pkl --repro --skfold 4/5 --name ${{ steps.vars.outputs.sha_short }}_5repro1
        
    - name: 6 train.py --repro2  
      run: |
        python train.py --project ich_ci --cache cache.pkl --repro --skfold 4/5 --name ${{ steps.vars.outputs.sha_short }}_6repro2
        
        
    - name: 7 train.py --task tset
      run: |
        python train.py --project ich_ci --cache cache.pkl \
        --task test --weights ich_ci/${{ steps.vars.outputs.sha_short }}_4skfold/weights/best.strip.pt \
        --name ${{ steps.vars.outputs.sha_short }}_7test
     
    - name: 8 train.py --subset  
      run: |
        python train.py --subset 0.02 --data cifar10  \
        --project ich_ci --cache cache_cifar10_subset.pkl --repro --skfold 4/5 --name ${{ steps.vars.outputs.sha_short }}_8subset
     
    - name: 9 train.py --cache auto  
      run: |
        python train.py --cache auto \
        --subset 0.8 --data cifar2  \
        --project ich_ci --cache cache_cifar10_subset.pkl --repro --skfold 4/5 --name ${{ steps.vars.outputs.sha_short }}_8subset
     
        
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
        
